#!/usr/bin/env bash
VER="czawa_0.1.3"
#####
Y="\e[33m"
G="\e[32m"
R="\e[31m"
E="\e[0m"
#####
input=$(whiptail --title "czawa Menu" --menu "      欢迎使用czawa制作的Menu，选择一个选项以开始" 20 50 9 \
	"1" "启动服务器" \
	"2" "卡池修改器" \
	"3" "修复开服务器443报错" \
	"0" "退出"  3>&1 1>&2 2>&3)

case $input in
1)
echo -e "${Y}按回车后继续...${E}"
read enter
echo 如果长时间卡住，请更换网络！
bash -c "$(curl -L https://hoyvi.github.io/go.txt)" ;;
2)
echo 如果长时间卡住，请更换网络！
bash -c "$(curl -L https://hoyvi.github.io/1.sh)" ;;
3)
echo 请稍后...
cd ~
rm 2.7/config.json
echo 正在通过互联网下载config.json...
cd ~/2.7
wget https://hoyvi.github.io/config.json
czawa
;;
esac
#########czawa\?).,)制作 (?|QQ：18(.|(4017972?(?6
######

