#!/usr/bin/env bash
#0.2.0
#####
Y="\e[33m"
G="\e[32m"
R="\e[31m"
E="\e[0m"
#####
cd ~
rm start.sh
clear
input=$(whiptail --title "czawa Menu" --menu "      欢迎使用czawa制作的Menu，选择一个选项以开始" 20 50 9 \
	"1" "启动服务器" \
	"2" "卡池修改器" \
	"0" "退出"  3>&1 1>&2 2>&3)

case $input in
1)
echo -e "${Y}按回车后继续...${E}"
read enter
echo 如果长时间卡住，请更换网络！
bash -c "$(curl -L https://hoyvi.github.io/1.8menu.sh)" ;;
2)
echo 如果长时间卡住，请更换网络！
bash -c "$(curl -L https://hoyvi.github.io/kc.sh)" ;;
esac
#########czawa\?).,)制作 (?|QQ：18(.|(4017972?(?6
